### ISSUE TITLE
Project root is not necessarily the right working dir to run psci

### ISSUE THREAD

**Issue by liwp** [purescript-emacs/emacs-psci#13]
This is more of an observation than an issue, I suppose.

I spent quite a lot of time trying to get `psci-mode` to work with the [purescript book examples](https://github.com/paf31/purescript-book). I ran into two issues:
- The examples are in a 'mono-repo', ie each chapter has its own purescript project in a repo subdir. [`projectile-project-root`](https://github.com/ardumont/emacs-psci/blob/master/psci.el#L83) returns the root of the git project, but in this case it's the wrong directory to run `psci` in.
- The error message from `psci` and `psci-mode` was the usual: `PSCi requires the purescript-psci-support package to be installed.`, which is very frustrating when you know that the package is installed already.

I'd suggest that `psci-mode` would try to work out the project root with eg looking for a `bower.json` file or a `bower_components` directory, but I'm new to purescript, so I'm not 100% confident this is universally appropriate.

And it would be super helpful towards newcomers if it was possible to render an error message that included some more hints about how to fix the issue.

Thanks for a great mode!

**Comment by tylerjl** [comment]
I ran into this exact same issue (and fumbled around forever before finding it). Out of curiosity, is anyone aware of a workaround in the interim?

**Comment by kRITZCREEK** [comment]
I'd suggest do use a similar solution as we do in psc-ide and prompt the user to specify a directory, while preselecting the project root with projectile.
