### ISSUE TITLE
Move this repository into the purescript-emacs org

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript-emacs/emacs-psci#16]
Hey, I just created a new organisation at https://github.com/purescript-emacs. I'm hoping to collect the repositories I'm currently maintaining (psc-ide-emacs, purescript-mode) and this one, and invite all the people that have an interest, so that we always have enough people to review and merge pull requests.

I'd be happy to invite you too, if you still have an interest in PureScript!

**Comment by ardumont** [comment]
> Hey, I just created a new organisation at https://github.com/purescript-emacs. I'm hoping to collect the repositories I'm currently maintaining (psc-ide-emacs, purescript-mode) and this one, and invite all the people that have an interest, so that we always have enough people to review and merge pull requests.

Awesome.

> I'd be happy to invite you too, if you still have an interest in PureScript!

I do but don't have time anymore.

I also don't have the time to maintain this repository anymore.
I'd be happy to move it under purescript-emacs organization.

How do we proceed?

Cheers,

**Comment by kRITZCREEK** [comment]
You can open Settings > Scroll down to Transfer > And transfer the repo to `purescript-emacs`

**Comment by ardumont** [comment]
I tried as mentioned.
It failed with the following message:

```
You don’t have the permission to create repositories on purescript-emacs 
```

Shouldn't i be a member of that organization with creation rights before transferring it?

**Comment by kRITZCREEK** [comment]
You are absolutely right, sorry. I sent an invitation

**Comment by ardumont** [comment]
> You are absolutely right, sorry. I sent an invitation

no worry.
There, joined and transferred ownership to the orga \m/.

And it's now a public repository.
Issues and PR still there :)

Cheers,

**Comment by kRITZCREEK** [comment]
Awesome! Thanks :)
